name: GitHub Actions Hello World
on: [push]
jobs:
  Checkout:
    steps:	
     - uses: actions/checkout@v2
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  Maven-Package:
    runs-on: ubuntu-latest
    steps:
      - run: ./mvnw package
  
