name: GitHub Actions Hello World
on:
 push:
  branches:
    - master
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  Maven-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./mvnw package
      - uses: actions/upload-artifact@v2
        with:
          name: target
          path: ./target/
  Build-And-Push-Image:
    environment: Grad-secrets
    runs-on: ubuntu-latest
    needs: Maven-Package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: target
          path: ./target/
      - run: docker build -t eu.gcr.io/sandpit-james-jeffrey-xtck/goose:$GITHUB_SHA .
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: push-to-gcr
        run: docker push eu.gcr.io/sandpit-james-jeffrey-xtck/goose
