name: GitHub Actions Hello World
on: [push]
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  Maven-Package:
    runs-on: ubuntu-latest
    steps:
      - run: ./mvnw package
